name: TheHOTRink
favicon: null
layout_spectrum: 0.16985956439748406
typography_spectrum: 0.4380681421607733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3510217627044767
  lightness: 0.8882233372423798
  saturation: 0.5969980736263096
  rhythmicContrast: 0.8814448569901288
purpose: []
